on:
  pull_request:
    paths:
      - '*.swift'
      - .github/workflows/ci.yml
  schedule:
    - cron: '3 3 * * 6'  # 3:03 AM, every Saturday
jobs:
  build:
    runs-on: macos-10.15
    strategy:
      matrix:
        xcode: [^10, ^11, ^12]
        conf: [release, debug]
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}
    - uses: actions/checkout@v2
    - run: swift build --configuration ${{ matrix.conf }} -Xswiftc -warnings-as-errors
