on:
  pull_request:
    paths:
      - '*.swift'
      - .github/workflows/ci.yml
  schedule:
    - cron: '3 3 * * 6'  # 3:03 AM, every Saturday
jobs:
  build:
    runs-on: macos-10.15
    strategy:
      matrix:
        xcode: [^10, ^11, ^12]
        conf: [release, debug]
        platform: [macOS, watchOS, iOS, tvOS]
    steps:
    - uses: actions/checkout@v2
    - uses: mxcl/xcodebuild@v1
      with:
        xcode: ${{ matrix.xcode }}
        platform: ${{ matrix.platform }}
        action: build
        configuration: ${{ matrix.conf }}
        warnings-as-errors: true
